# Information
site_name: 'SeAT Discourse Documentation'
site_description: 'Simple EVE Api Tool Discourse Documentation'
site_url: 'https://github.com/herpaderpaldent/seat-discourse'

# Repository
repo_name: 'herpaderpaldent/seat-discourse'
repo_url: 'https://github.com/herpaderpaldent/seat-discourse'

# Copyright
copyright: 'Copyright &copy; 2018 Felix Huber'

# Documentation TOC
pages:
    - Home: index.md
    - Discourse Installation: installation/discourse_installation.md
    - Proxy Server Configuration:
        - traefik: installation/proxy_server/traefik.md
        - nginx: installation/proxy_server/nginx.md
    - Package Installation: installation/package_installation.md
#        - CentOS: guides/installation/manual_installation/centos.md
#        - Debian: guides/installation/manual_installation/debian.md
#        - Docker: guides/installation/manual_installation/docker.md
#        - Manual: guides/installation/manual_installation/manual.md
#        - Ubuntu: guides/installation/manual_installation/ubuntu.md

# Theme Configuration
theme:
    name: 'material'
    palette:
        primary: 'grey'
        accent: 'indigo'


# Customization
markdown_extensions:
    - admonition
    - codehilite
    - toc:
        permalink: true
extra:
  social:
    - type: 'github'
      link: 'https://github.com/herpaderpaldent/seat-discourse'
# Tabs customisation
extra_css:
    - css/extra_typo.css
    - css/extra_tabs.css
extra_javascript:
    - js/extra_tabs.js
